server:
  context-path: @api.base.context-path@
  port: 8081
  session:
    timeout: @session.timeout@  # in seconds
    cookie:
      max-age: @cookie.max-age@ # in seconds
    
#management:
#  port: 8083
#  security:
#    enabled: false

spring:
  main:
    web-environment: true
  mail:
    host: @mail.host@
    port: @mail.port@
    username: @mail.username@
    password: @mail.password@
    properties:
      mail.smtp.auth: @mail.smtp.auth@
      mail.smtp.starttls.enable: @mail.smtp.starttls.enable@
    test-connection: @mail.test-conection@
  jpa:
    hibernate:
      ddl-auto: @main.db.jpa.mode@
    show-sql: true
    generate-ddl: true
    properties:
      hibernate.type: trace
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: @main.db.jdbc.url@
    username: @main.db.user@
    password: @main.db.password@
    driver-class-name: @main.db.driver.name@
    hikari:
      maximum-pool-size: 30
    platform: @main.db.platform@
  smaxDatasource:
    url: @smax.db.jdbc.url@
    username: @smax.db.user@
    password: @smax.db.password@
    driver-class-name: @smax.db.driver.name@
    hikari:
      maximum-pool-size: 30

  thymeleaf:
    enabled: false #disabled MVC
security:
  basic:
    enabled: true
#    Since we are using GMAIL, we have to use the same email address because GMAIL doesn't allow to change the FROM property
email:
  from: @email.from@
website:
  url: @website.base.url@
  context-path: @website.base.context-path@
logging:
  config: classpath:logback.xml

property:
  load:
    test: Working


google:
  recaptcha:
    secret: @google.recaptcha.secret.key@
    active: @google.recaptcha.activate@
oracle:
  proxy:
    host: @oracle.proxy.host@
    port: @oracle.proxy.port@

smax:
  interface:
    use: @smax.interface.in-use@

#move this to a different properties file
messages:
  general:
    unknown.error: "Error Desconocido"
    missing.required.fields: "Faltan campos requeridos"
  search:
    student.missing.required.fields: "Falta campos requerido Fecha de Nacimiento, (Ultimo SSN o Numero Estudiante) y Nombre"
  user:
    already.exists: "Usuario existente"
    min.age.validation: "Usuario debe tener 18 años o mas"
    reset.password.invalid: "No se pudo completar el reinicio de su contraseña"
    password.mismatch: "Contraseñas no coinciden"
    error.saving.profile: "Error al grabar datos del usuario"
    invalid.forgot.password.request: "Solicitud de cambio de contraseña invalida"
    cancel.reset.password.invalid: "Solicitud de cancelar reinicio de contraseña invalida"



